server:
  port: 9999

security:
  oauth2:
    client:
      client-id: testclient
      client-secret: secret
      scope: openid
logging:
  level:
    org:
      springframework:
        security: trace

